appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: dCw32oonPl+Q850frQ0vW+5DZu/dBeNs352BDu2d5onciKCR307GmvTBo3AccSLMIH12LdcjurSbyBoxjgo42cruuOebWC0lGGDJXUTjOn/vKg7VeDxo+Q3HWXj0dxbMmH6VgekDaAF1+QtatlBuQZLXMkyhkMAQp4/LcoM9Xcl7gwKhhZo+nYlL66+H78d0jnhTI5g5SNBFNhpd5/luv7BVjQDQwBOP+0ByeYYbNBShOyTt1J36XSiQ6fcHDTY+HPhj0n2Y9l7nc3/+VCCECgOcjVWBTynBx5xSeqVFb9FYKPyjT/XlHvqnEdWhdaaosUbtPxfthIN0C/FwaiNmU6L9kQG6W77ag9ITz2ooFzokyCSm4fADKPuAudL53RrxHYRQuXoHwsB+9BMRni2N/Q7WD4nsWhwUCwXj7JwO5Z3OKqIFwMrLSrFqzwxikjoOJuEG9tmVZAQpcGVI0R72FqeGtahqEs3RKRR7ym2K3EokqH/u6te0fk3O9Io6HVAWbowWtRzJPg7CrYwv5Heute8d99LYKIgnb1s5w0rYcayRddZN9BT37Q3gYdhEj5oN0SSxzyRGPMUDzyj/IiNRvxsf6OEIDY/zpsDbGozpiPIm9+nbilBtQWZVhdSNu99yzSbUZbS/sLeg2/LbeYKSK9AtGABp2OfBiJySPMMBq0Y=
